name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Copy assets
        run: cp -r assets dist/
        
      - name: Create main.js with correct imports for deployment
        run: |
          # Create a completely new main.js file with correct imports
          cat > dist/main.js << 'EOL'
          import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.177.0/build/three.module.js';
          import { PointerLockControls } from 'https://cdn.jsdelivr.net/npm/three@0.177.0/examples/jsm/controls/PointerLockControls.js';
          import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.177.0/examples/jsm/loaders/GLTFLoader.js';

          // Rest of the main.js content
          EOL
          
          # Append the rest of main.js (skipping the first 3 lines which are the imports)
          tail -n +4 main.js >> dist/main.js
        
      - name: Create index.html for deployment
        run: |
          cat > dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Cooking Island (Lite)</title>
              <style>
                  body {
                      margin: 0;
                      overflow: hidden;
                      font-family: Arial, sans-serif;
                  }
                  canvas {
                      display: block;
                  }
                  #loadingMessage {
                      position: absolute;
                      top: 50%;
                      left: 50%;
                      transform: translate(-50%, -50%);
                      font-size: 24px;
                      color: white;
                      background-color: rgba(0, 0, 0, 0.7);
                      padding: 20px;
                      border-radius: 10px;
                      text-align: center;
                  }
                  #startButton {
                      position: absolute;
                      top: 50%;
                      left: 50%;
                      transform: translate(-50%, -50%);
                      font-size: 18px;
                      padding: 10px 20px;
                      background-color: #4CAF50;
                      color: white;
                      border: none;
                      border-radius: 5px;
                      cursor: pointer;
                      display: none;
                  }
              </style>
          </head>
          <body>
              <div id="loadingMessage">Loading 3D scene...</div>
              <button id="startButton" style="display:none;">Click to Start</button>
              <script type="module" src="main.js"></script>
          </body>
          </html>
          EOL
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }} 